baseURL = 'https://pragmatechdad.blog/'
languageCode = 'en-us'
DefaultContentLanguage = "en"
title = 'Pragmatech Dad Blog'
theme = 'hugo-paper'
author = 'jcvincent'
copyright = "© 2025, jcvincent"


[pagination]
  pagerSize = 5

[params]
    contentTypeName = 'posts'
    color = 'linen'

[taxonomies]
category = "categories"
tag = "tags"

[menu]

  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 10

